MONGODB_URL = "mongodb://127.0.0.1:27017/"
MONGODB_DB_NAME = "anonymizer"
MAX_CONNECTIONS_COUNT = 10
MIN_CONNECTIONS_COUNT = 1
JWT_TOKEN_PREFIX = "Token"
SECRET_KEY = ""
ACCESS_TOKEN_EXPIRE_MINUTES = 60 * 24 * 7  # one week
